

$$minimize \sum_{(i,j)\in E} c_{ij} x_{ij}$$

$$s.t.$$

$$\sum_{k|(j,k)\in E} x_{jk} - \sum_{k|(k,j)\in E} x_{kj} = 0\ , \forall j \in nodes$$

$$\sum_{k|(origin,k)\in E} x_{origin,k} = 1$$

$$\sum_{k|(k,destination)\in E} x_{k,destination} = 1$$

$$0 \leq x_{ij} \leq 1, (i,j) \in E$$

In [108]:
#b

import numpy as np, opt111, matplotlib.pyplot as plt

c = np.matrix([[0,40,60,50,0,0,0],[40,0,10,0,70,0,0],[60,0,0,20,55,40,0],[50,0,20,0,0,50,0],[70,55,0,0,0,10,60],[0,0,40,50,10,0,80],[0,0,0,0,0,0,0]])
u = np.zeros(c.shape)
u[c>0] = 1
b = np.matrix([1,0,0,0,0,0,-1]).T

optimal, flow = opt111.min_cost_flow(c, u, b)

Optimization terminated successfully.


In [109]:
optimal

matrix([[ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [110]:
flow

160.0

c)

we can adjust our cost function to represent time rather than distance, but we do not have to adjust any of our constraints.

therefore, this won't change the solution, and we still end up with the same result as the above.

d)

here, we actually have to switch to a maximum flow problem

so we will likely get a different result

$$maximize \sum_{j|(origin,j)\in E} c_{origin,j}$$

$$s.t.$$

$$\sum_{k|(j,k)\in E} x_{jk} - \sum_{k|(k,j)\in E} x_{kj} = 0 , \forall j \in nodes$$

$$0 \leq x_{ij} \leq c_{ij}, (i,j) \in E$$

see below result:

In [111]:
#d continued

import numpy as np, opt111, matplotlib.pyplot as plt

u = np.matrix([[0,40,60,50,0,0,0],[0,0,10,0,70,0,0],[0,0,0,20,55,40,0],[0,0,0,0,0,50,0],[0,0,0,0,0,10,60],[0,0,0,0,0,0,80],[np.inf,0,0,0,0,0,0]])
c = np.zeros(c.shape)
c[6][0] = -1
b = np.matrix([0,0,0,0,0,0,0]).T

optimal, flow = opt111.min_cost_flow(c,u,b)

Optimization terminated successfully.


In [112]:
optimal

matrix([[   0.,   40.,   60.,   40.,    0.,    0.,    0.],
        [   0.,    0.,    0.,    0.,   40.,    0.,    0.],
        [   0.,    0.,    0.,    0.,   20.,   40.,    0.],
        [   0.,    0.,    0.,    0.,    0.,   40.,    0.],
        [   0.,    0.,    0.,    0.,    0.,    0.,   60.],
        [   0.,    0.,    0.,    0.,    0.,    0.,   80.],
        [ 140.,    0.,    0.,    0.,    0.,    0.,    0.]])

In [113]:
-flow

140.0


$$minimize \sum_{(i,j)\in E} c_{ij} x_{ij}$$

$$s.t.$$

$$\sum_{k|(j,k)\in E} x_{jk} - \sum_{k|(k,j)\in E} x_{kj} = 0 , \forall j \in nodes$$

$$\sum_{k|(Source,k)\in E} x_{Source,k} = 5$$

$$\sum_{k|(k,Sink)\in E} x_{k,Sink} = 5$$

$$0 \leq x_{ij} \leq 1, (i,j) \in E$$


In [2]:
import numpy as np, new_opt111, matplotlib.pyplot as plt

cx = np.matrix([[37.7,32.9,33.8,37.0,35.4],[43.4,33.1,42.2,34.7,41.8],[33.3,28.5,38.9,30.4,33.6],[29.2,26.4,29.6,28.5,31.1],[0,0,0,0,0]])
ux = np.ones(cx.shape)

b = np.matrix([1,1,1,1,1,-1,-1,-1,-1,-1]).T
Z = np.zeros((5,5))
c = np.bmat([[Z, cx], [Z, Z]])
u = np.bmat([[Z, ux], [Z, Z]])
print c.shape
print u.shape
print b.shape
optimal, flow = new_opt111.min_cost_flow(c, u, b)

(10, 10)
(10, 10)
(10, 1)
Optimization terminated successfully.


In [115]:
optimal

matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [116]:
flow

126.19999999999999

a)

$$minimize \sum_{i=1}^{n}\sum_{j=1}^{n} c_{ij} x_{ij}$$

$$s.t.$$

$$\sum_{k|(j,k)\in E} x_{jk} - \sum_{k|(k,j)\in E} x_{kj} = 0 , \forall j \in nodes$$

$$\sum_{k|(origin,k)\in E} x_{origin,k} = n$$

$$\sum_{k|(k,destination)\in E} x_{k,destination} = n$$

$$0 \leq x_{ij} \leq 1, (i,j) \in E$$

b)

Yes, we know that the solution will be an integer solution, because each edge (i,j) is also integral, and thus: 

$$m^{j}_{i}\ and\ w^{i}_{j}\ will\ also\ be\ integers$$

Since c is just m * w, then we know that c will be an integer as well

In [117]:
#c

import numpy as np, new_opt111, matplotlib.pyplot as plt
from rankings import women_rankings, men_rankings

cx = np.multiply(women_rankings, men_rankings.T)
ux = np.ones(cx.shape)

b = np.matrix([1,1,1,1,1,1,-1,-1,-1,-1,-1,-1]).T
Z = np.zeros((6,6))
c = np.bmat([[Z, cx], [Z, Z]])
u = np.bmat([[Z, ux], [Z, Z]])

optimal, flow = new_opt111.min_cost_flow(c, u, b)

Optimization terminated successfully.


In [118]:
optimal

matrix([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [119]:
flow

24.0

d)

product matching isn't stable. 

man 5 is matched to 6 but should be matched to 1.

woman 1 is matched to 6 but should be matched to 5.